services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        VITE_API_BASE_URL: "https://beerbears.website"
    container_name: tender-hack-frontend
    ports:
      - "90:90"
    restart: unless-stopped
