import { http, HttpResponse, delay } from 'msw'

export const documentHandlers = [
  // POST /api/documents/generate
  http.post('/api/documents/generate', async () => {
    await delay(500)

    return HttpResponse.json({
      file_url: '/api/documents/download/mock-doc-001',
      generated_at: new Date().toISOString(),
    })
  }),

  // GET /api/documents/download/:docId
  http.get('/api/documents/download/:docId', () => {
    const content = 'Mock NMCK justification document — generated by MSW mock server.'
    return new HttpResponse(content, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': 'attachment; filename="nmck-justification.txt"',
      },
    })
  }),
]
